### ISSUE TITLE
Errore "LedControl.h"

### ISSUE THREAD

**Issue by federicobracco** [karonth/bottino#1]
Buonasera, oggi alla Mini Maker Fair ho assemblato con il suo aiuto un Bottino. Ho quindi seguito le istruzioni ed ho installato il programma (Arduino 1.8.2) con i gestori del collegamento a Telegram nella libreria apposita e i driver USB; quando però, dopo aver compilato come da istruzioni il codice bottino.ino, vado a verificarne la correttezza il programma da errore dicendo:
C:\Users\Name\Desktop\sketch_may28a\sketch_may28a.ino:18:24: fatal error: LedControl.h: No such file or directory

 #include "LedControl.h"

                        ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.
Come posso risolvere?

**Comment by karonth** [comment]
Buonasera, avevo dimenticato di aggiungere tra le librerie richieste anche quella LedControl, che contiene il codice per il controllo della matrice a led, rimedio subito. 
Una piccola nota: certe versioni della librerie LedControl possono dare un errore sull'include di avr\pgmspace.h

in questo caso basta modificare il file LedControl.h sostituendo:

#include <avr\pgmspace.h>

con

#if (defined(AVR))
#include <avr\pgmspace.h>
#else
#include <pgmspace.h>
#endif

Su github questa soluzione è stata implementata https://github.com/wayoda/LedControl/issues/10#issuecomment-290219444

**Comment by federicobracco** [comment]
Problema risolto per il LedControl ma mi blocco di nuovo; ora mi dice:

"sketch_may28a:19: error: 'D4' was not declared in this scope

LedControl lc=LedControl(D4,D2,D3,1);

                          ^

sketch_may28a:19: error: 'D2' was not declared in this scope

 LedControl lc=LedControl(D4,D2,D3,1);

                             ^

sketch_may28a:19: error: 'D3' was not declared in this scope

 LedControl lc=LedControl(D4,D2,D3,1);

                                ^

exit status 1
'D4' was not declared in this scope"

Probabilmente sono errori dovuti alla mia inesperienza e mi scuso per il ripetuto disurbo.

**Comment by karonth** [comment]
Questo può essere dovuto al tipo di scheda scelta nell'ide Arduino: bisogna selezionare Wemos D1 mini.
Quale versione del core esp8266 è installata?

**Comment by federicobracco** [comment]
Risolto grazie mille!
